# Generated by Django 5.1.3 on 2025-10-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignlanguage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Язык'),
        ),
    ]
