# Generated by Django 5.1.3 on 2025-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_education_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialty',
            field=models.CharField(blank=True, default='-', max_length=1023, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='occupation',
            field=models.CharField(blank=True, default='-', max_length=1023, verbose_name='Профессия / род занятий'),
        ),
    ]
