# Generated by Django 5.1.3 on 2025-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_education_specialty_registrationform_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(max_length=1023, verbose_name='Месяц и год начала работы'),
        ),
    ]
