# Generated by Django 5.1.3 on 2025-11-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_workexperience_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
