# Generated by Django 5.1.3 on 2026-03-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Взаимодействует'),
        ),
        migrations.AddField(
            model_name='user',
            name='reason_unavailable',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Причина невзаимодействия'),
        ),
    ]
