
import {defineConfig, loadEnv} from 'vite';
import react from '@vitejs/plugin-react';
import federation from '@originjs/vite-plugin-federation';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, '.', '');
    return {
  plugins: [
    react(),
    federation({
      name: 'host-app',
      remotes: {
        // The remote app 'auth' is configured to be loaded from this URL.
        // The URL points to the remoteEntry.js file generated by the remote app.
        auth: `http://${env.VITE_FRONTEND_AUTH_HOST}/assets/remoteEntry.js`,
        registration_form: 'http://localhost:84/assets/remoteEntry.js',
      },
      // Shared dependencies to avoid loading them multiple times.
      shared: ['react', 'react-dom'],
    }),
  ],
  // Recommended build options for module federation to work smoothly.
  build: {
    modulePreload: false,
    target: 'esnext',
    minify: false,
    cssCodeSplit: false,
  }
}})
