# Generated by Django 5.1.3 on 2025-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldpr_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Среднее общее', 'Среднее общее'), ('Среднее профессиональное', 'Среднее профессиональное'), ('Высшее', 'Высшее')], max_length=100, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='postgraduate_type',
            field=models.CharField(blank=True, choices=[('Аспирантура', 'Аспирантура'), ('Ординатура', 'Ординатура'), ('Докторантура', 'Докторантура')], max_length=100, verbose_name='Вид послевузовского образования'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='level',
            field=models.CharField(choices=[('Читаю и перевожу со словарем', 'Читаю и перевожу со словарем'), ('Читаю и могу объясняться', 'Читаю и могу объясняться'), ('Свободно владею', 'Свободно владею')], max_length=100, verbose_name='Уровень владения'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='committee_status',
            field=models.CharField(choices=[('Член', 'Член'), ('Председатель', 'Председатель'), ('Заместитель', 'Заместитель')], max_length=50, verbose_name='Статус в комиссии или комитете'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='representative_body_level',
            field=models.CharField(choices=[('Совет Федерации Федерального собрания Российской Федерации', 'Совет Федерации Федерального собрания Российской Федерации'), ('Государственная дума Федерального собрания Российской Федерации', 'Государственная дума Федерального собрания Российской Федерации'), ('ЗС', 'ЗС'), ('АЦС', 'АЦС'), ('МСУ', 'МСУ')], max_length=80, verbose_name='Уровень представительного органа'),
        ),
        migrations.AlterField(
            model_name='russianfederationlanguage',
            name='level',
            field=models.CharField(choices=[('Читаю и перевожу со словарем', 'Читаю и перевожу со словарем'), ('Читаю и могу объясняться', 'Читаю и могу объясняться'), ('Свободно владею', 'Свободно владею')], max_length=100, verbose_name='Уровень владения'),
        ),
    ]
