# Generated by Django 5.1.3 on 2025-09-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ldpr_form', '0002_alter_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='telegram_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('role', models.CharField(choices=[('deputy', 'Депутат'), ('coordinator', 'Координатор'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последний вход')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='ldpr_user_set', related_query_name='ldpr_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ldpr_user_permissions_set', related_query_name='ldpr_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='registrationform',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deputy_form', serialize=False, to='ldpr_form.user'),
            preserve_default=False,
        ),
    ]
