# Generated by Django 5.1.3 on 2025-09-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldpr_form', '0003_remove_registrationform_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('deputy', 'Депутат'), ('coordinator', 'Координатор'), ('admin', 'Администратор')], default='deputy', max_length=20, verbose_name='Роль'),
        ),
    ]
