# Generated by Django 5.1.3 on 2025-09-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldpr_form', '0004_alter_user_role'),
    ]

    operations = [
    ]
