import os

CHAT_ID = os.getenv("CHAT_ID")
BASE_URL = os.getenv("BASE_URL")
BOT_TOKEN = os.getenv('BOT_TOKEN')
ERROR_LOG_CHAT_ID = os.getenv("ERROR_LOG_CHAT_ID", "")
INFO_LOG_CHAT_ID = os.getenv("INFO_LOG_CHAT_ID", "")
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE")
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_USERNAME = os.getenv("DATABASE_TG_USERNAME")
DATABASE_PASSWORD = os.getenv("DATABASE_TG_PASSWORD")
DATABASE_PORT = os.getenv("DATABASE_TG_PORT")
