# Generated by Django 5.1.3 on 2025-10-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('is_available', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('level', models.CharField(choices=[('MCU', 'Депутаты муниципальных образований'), ('ACR', 'Депутаты административных центров регионов'), ('ZS', 'Депутаты Законодательных собраний регионов')])),
                ('reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Причина невзаимодействия')),
            ],
            options={
                'verbose_name': 'Запись депутата',
                'verbose_name_plural': 'Записи депутатов',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер поля')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название поля')),
                ('theme', models.CharField(choices=[('infoudar', 'Инфоудар'), ('vdpg', 'ВДПГ'), ('event', 'Мероприятие'), ('reg_event', 'Мероприятие в рег. парламенте'), ('letter', 'Письмо')])),
            ],
            options={
                'verbose_name': 'Поле отчёта',
                'verbose_name_plural': 'Поля отчёта',
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Отчётный период',
                'verbose_name_plural': 'Отчётные периоды',
            },
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Отчёт депутата',
                'verbose_name_plural': 'Отчёты депутата',
            },
        ),
    ]
