# Generated by Django 5.1.3 on 2025-10-13 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month_report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deputyrecord',
            name='deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vdpg_reports', to='month_report.reportperiod'),
        ),
        migrations.AddField(
            model_name='deputyrecord',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputies_records', to='month_report.reportperiod'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='deputy_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='month_report.deputyrecord'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='month_report.report'),
        ),
    ]
