# Generated by Django 5.1.3 on 2025-11-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_report', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputyrecord',
            name='report_period',
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='RegionReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('report_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_reports', to='month_report.reportperiod')),
            ],
        ),
        migrations.AddField(
            model_name='deputyrecord',
            name='region_report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='deputies_records', to='month_report.regionreport'),
            preserve_default=False,
        ),
    ]
