# Generated by Django 5.1.3 on 2025-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_report', '0003_remove_deputyrecord_report_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyrecord',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regionreport',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Номер поля'),
        ),
        migrations.AlterField(
            model_name='reportperiod',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
