# Generated by Django 5.1.3 on 2025-11-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_report', '0005_alter_deputyrecord_id_alter_regionreport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyrecord',
            name='level',
            field=models.CharField(choices=[('Совет Федерации Федерального собрания Российской Федерации', 'Совет Федерации Федерального собрания Российской Федерации'), ('Государственная дума Федерального собрания Российской Федерации', 'Государственная дума Федерального собрания Российской Федерации'), ('ЗС', 'ЗС'), ('АЦС', 'АЦС'), ('МСУ', 'МСУ')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='month_report.reportperiod'),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
