# Generated by Django 5.1.3 on 2025-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_report', '0006_alter_deputyrecord_level_alter_report_report_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='theme',
            field=models.CharField(choices=[('infoudar', 'Инфоудар'), ('vdpg', 'ВДПГ'), ('event', 'Мероприятие'), ('reg_event', 'Мероприятие в рег. парламенте'), ('opt_event', 'Опциональное мероприятие'), ('letter', 'Письмо')]),
        ),
    ]
