# Generated by Django 5.1.3 on 2026-03-27 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_report', '0008_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='score_explanation',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Объяснение оценки'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает проверки'), ('in_process', 'Проверяется'), ('processed', 'Проверено')], default='waiting', max_length=20, verbose_name='Статус проверки'),
        ),
    ]
